### ISSUE TITLE
Config load error

### ISSUE THREAD

**Issue by CountParadox** [altillimity/Auto137#2]
After making the change in the readme to resolve the config load error, I now get a different one..

`
-----------------------------------------
            Starting Auto137
-----------------------------------------

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    config.loadConfig("config.yaml")
  File "/home/lmartin/Auto137/config.py", line 30, in loadConfig
    config = yaml.load(f)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "config.yaml", line 4, column 3
expected <block end>, but found '<block sequence start>'
  in "config.yaml", line 14, column 4
lmartin@autowx2:~/Auto137$
`

**Comment by CountParadox** [comment]
The only changes I made in the config were the path to export, the coordinates and turning web server to true

**Comment by Aang23** [comment]
Could you send your config.yaml?

**Comment by CountParadox** [comment]
Yep, 

its:

```
# Define your satellites here! Options names should be self-explanatory
satellites:
  - sat:
    name: NOAA 15
    norad: 25338
    priority: 0
    min_elevation: 10
    frequency: 137.620
    downlink: APT
    delete_processed_files: true


   - sat:
    name: NOAA 18
    norad: 28654
    priority: 0
    min_elevation: 10
    frequency: 137.9125
    downlink: APT
    delete_processed_files: true
  - sat:
    name: NOAA 19
    norad: 33591
    priority: 0
    min_elevation: 10
    frequency: 137.100
    downlink: APT
    delete_processed_files: true
  - sat:
    name: METEOR-M 2 
    norad: 40069
    priority: 1
    min_elevation: 20
    frequency: 137.100
    downlink: LRPT
    delete_processed_files: true
config:
  # How often should TLE data be updated?
  tle_update_interval: 1
  # Where will images and temporary files be stored
  output_dir: "/var/www/html"
  # Your location
  station:
    latitude: -33.810429
    longitude: 150.989624
    elevation: 16
  # Optional RSS feed. Using a webserver such as NGINX or Apache2 is recommended
  rss:
    enabled: true
    webserver: true
    port: 8080
  # Run a command once files (images or raw) or done being processed
  post_processing_hook:
    # You can set any command here. {file} will be replace by the path to the file in the following format '/path/to/file'
    command: "scp {file} user@remoteserver:/sample"
    enabled: false
    # If enabled the command will be ran once for each output file. If set to false {file} will instead be replaced by a series of paths, eg. '/path/to/file1' '/path/to/file2'
    run_foreach: true
  # Maximum overlap in minutes before a pass is entirely ignored
  max_overlap: 7
```

Cant get it to format properly...see: https://paste.ubuntu.com/p/7jmzXFkhmC/
